services:
  mongo:
    image: mongo:6.0.13
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db:/data/db
  app:
    build:
      context: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  db:

